import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { getStationForecast } from '../../data/mockData';
import { PrototypeBadge } from '../common/PrototypeBadge';
import {
  TrendingUp,
  Clock,
  Wind,
  Layers,
  Thermometer,
  Compass,
  MapPin,
  AlertTriangle,
  Sparkles,
  Info
} from 'lucide-react';

export const ForecastView: React.FC = () => {
  const { stations, selectedStationId, setSelectedStationId } = useApp();

  const [activeMetric, setActiveMetric] = useState<'aqi' | 'pm25' | 'pm10'>('aqi');

  const currentStation =
    stations.find(s => s.id === selectedStationId) || stations[0];

  const forecast = getStationForecast(currentStation);

  // Extract key milestone points
  const currentObserved = forecast.dataPoints.find(p => p.hourOffset === 0);
  const plus6h = forecast.dataPoints.find(p => p.hourOffset === 6);
  const plus12h = forecast.dataPoints.find(p => p.hourOffset === 12);
  const plus24h = forecast.dataPoints.find(p => p.hourOffset === 24);
  const plus48h = forecast.dataPoints.find(p => p.hourOffset === 48);

  // SVG Chart Dimensions
  const chartWidth = 720;
  const chartHeight = 240;
  const paddingX = 45;
  const paddingY = 35;

  const points = forecast.dataPoints;
  const minVal = Math.min(...points.map(p => p[activeMetric])) * 0.85;
  const maxVal = Math.max(...points.map(p => p[activeMetric])) * 1.15;

  const getX = (index: number) => {
    return paddingX + (index / (points.length - 1)) * (chartWidth - 2 * paddingX);
  };

  const getY = (val: number) => {
    return (
      chartHeight -
      paddingY -
      ((val - minVal) / (maxVal - minVal || 1)) * (chartHeight - 2 * paddingY)
    );
  };

  const observedPoints = points.filter(p => p.type === 'observed');
  const predictedPoints = points.filter(p => p.type === 'predicted');
  const nowIndex = points.findIndex(p => p.hourOffset === 0);

  // Path generator for observed points
  const observedPath = observedPoints
    .map((p, idx) => `${idx === 0 ? 'M' : 'L'} ${getX(idx)} ${getY(p[activeMetric])}`)
    .join(' ');

  // Path generator for predicted points (starts from nowIndex)
  const predictedPath = [points[nowIndex], ...predictedPoints]
    .map((p, idx) => `${idx === 0 ? 'M' : 'L'} ${getX(nowIndex + idx)} ${getY(p[activeMetric])}`)
    .join(' ');

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900/90 p-5 rounded-2xl border border-slate-800 shadow-xl">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <TrendingUp className="w-5 h-5 text-teal-400" />
            <h1 className="text-xl lg:text-2xl font-extrabold text-white tracking-tight">
              Pollution Forecasting & Trajectory Horizon
            </h1>
            <PrototypeBadge variant="prediction" label="MODEL PREDICTION" />
          </div>
          <p className="text-xs text-slate-400">
            Spatio-temporal atmospheric forecast integrating WRF-Chem dispersion models, boundary layer dynamics, and historical diurnal recurrence.
          </p>
        </div>

        {/* Station Selector */}
        <div className="flex items-center gap-2">
          <MapPin className="w-4 h-4 text-teal-400" />
          <span className="text-xs text-slate-400 font-medium">Select Station:</span>
          <select
            value={currentStation.id}
            onChange={e => setSelectedStationId(e.target.value)}
            className="bg-slate-800 border border-slate-700 text-slate-200 text-xs rounded-xl px-3 py-2 font-medium focus:outline-none focus:border-teal-500 shadow-sm"
          >
            {stations.map(st => (
              <option key={st.id} value={st.id}>
                {st.name} — {st.district} (AQI {st.aqi})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Scientific Transparency Disclaimer */}
      <div className="p-4 rounded-xl bg-purple-950/30 border border-purple-800/60 text-purple-200 text-xs space-y-1.5 shadow-md">
        <div className="flex items-center gap-2 font-bold text-purple-300">
          <Sparkles className="w-4 h-4 text-purple-400 shrink-0" />
          <span>Predictive Modeling Disclosure</span>
          <PrototypeBadge variant="prototype" label="SIMULATED PROJECTION" />
        </div>
        <p className="leading-relaxed text-[11px] text-purple-200/90">
          Forecast horizons (+6h, +12h, +24h, +48h) are generated by a <strong>prototype predictive atmospheric model</strong>. These are simulated research projections to assess risk windows and are <strong>not official meteorological forecasts</strong> from the India Meteorological Department (IMD) or SAFAR.
        </p>
      </div>

      {/* Station Overview & Micro-Meteorology Conditions */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-3.5">
        <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-xl">
          <div className="text-[10px] text-slate-400 uppercase font-mono">Current Observed AQI</div>
          <div className="text-2xl font-black text-white font-mono mt-1 flex items-baseline gap-2">
            <span>{currentStation.aqi}</span>
            <span
              className={`text-xs font-semibold px-2 py-0.5 rounded ${
                currentStation.aqi > 400
                  ? 'bg-rose-950 text-rose-300 border border-rose-800'
                  : 'bg-amber-950 text-amber-300 border border-amber-800'
              }`}
            >
              {currentStation.aqi > 400 ? 'Hazardous' : 'Severe'}
            </span>
          </div>
          <div className="text-[10px] text-slate-400 mt-2 flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-emerald-400" />
            <span>Observed CAAQMS Sensor</span>
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-xl">
          <div className="text-[10px] text-slate-400 uppercase font-mono">Atmospheric Inversion Risk</div>
          <div className="text-2xl font-black text-amber-400 font-mono mt-1">
            {forecast.inversionRisk}
          </div>
          <div className="text-[10px] text-slate-400 mt-2">
            Surface boundary trap: <strong className="text-slate-300 font-mono">{forecast.boundaryLayerHeightMeters}m</strong>
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-xl">
          <div className="text-[10px] text-slate-400 uppercase font-mono">Wind Dispersion Index</div>
          <div className="text-2xl font-black text-cyan-300 font-mono mt-1">
            {forecast.windSpeedTrendKmh} <span className="text-xs font-normal text-slate-400">km/h</span>
          </div>
          <div className="text-[10px] text-slate-400 mt-2">
            Stagnation index: High calm hours
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-xl">
          <div className="text-[10px] text-slate-400 uppercase font-mono">Forecast Confidence</div>
          <div className="text-2xl font-black text-emerald-400 font-mono mt-1">
            {forecast.modelConfidence}%
          </div>
          <div className="text-[10px] text-slate-400 mt-2">
            Ensemble agreement score
          </div>
        </div>
      </div>

      {/* 5-Step Horizon Cards (Historical, Now, +6h, +12h, +24h, +48h) */}
      <div className="space-y-2">
        <div className="flex items-center justify-between text-xs font-semibold text-slate-300">
          <span>Pollution Trajectory Milestones</span>
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1.5 text-[11px] text-teal-300">
              <span className="w-2.5 h-2.5 rounded-full bg-teal-400" />
              <span>Observed Historical</span>
            </span>
            <span className="flex items-center gap-1.5 text-[11px] text-purple-300">
              <span className="w-2.5 h-2.5 rounded-full bg-purple-400" />
              <span>Model Predicted</span>
            </span>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {/* Observed Now */}
          <div className="p-3.5 rounded-xl bg-slate-900 border border-teal-500/60 shadow-md ring-1 ring-teal-500/20">
            <div className="flex items-center justify-between text-[10px] font-mono text-teal-400 mb-1">
              <span className="font-bold">CURRENT OBSERVED</span>
              <span className="px-1.5 py-0.5 rounded bg-teal-950 text-teal-300 border border-teal-800">
                0h
              </span>
            </div>
            <div className="text-xl font-black text-white font-mono">
              AQI {currentObserved?.aqi}
            </div>
            <div className="text-[11px] text-slate-400 mt-1">
              PM2.5: <strong className="text-slate-200 font-mono">{currentObserved?.pm25} µg</strong>
            </div>
            <div className="text-[10px] text-slate-500 font-mono mt-1">Verified Reference</div>
          </div>

          {/* +6-Hour Forecast */}
          <div className="p-3.5 rounded-xl bg-slate-900/90 border border-purple-800/60">
            <div className="flex items-center justify-between text-[10px] font-mono text-purple-300 mb-1">
              <span className="font-bold">6-HOUR FORECAST</span>
              <span className="px-1.5 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800">
                +6h
              </span>
            </div>
            <div className="text-xl font-black text-purple-200 font-mono">
              AQI {plus6h?.aqi}
            </div>
            <div className="text-[11px] text-slate-400 mt-1">
              PM2.5: <strong className="text-purple-300 font-mono">{plus6h?.pm25} µg</strong>
            </div>
            <div className="text-[10px] text-purple-400/80 font-mono mt-1">Nocturnal peak surge</div>
          </div>

          {/* +12-Hour Forecast */}
          <div className="p-3.5 rounded-xl bg-slate-900/90 border border-purple-800/60">
            <div className="flex items-center justify-between text-[10px] font-mono text-purple-300 mb-1">
              <span className="font-bold">12-HOUR FORECAST</span>
              <span className="px-1.5 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800">
                +12h
              </span>
            </div>
            <div className="text-xl font-black text-purple-200 font-mono">
              AQI {plus12h?.aqi}
            </div>
            <div className="text-[11px] text-slate-400 mt-1">
              PM2.5: <strong className="text-purple-300 font-mono">{plus12h?.pm25} µg</strong>
            </div>
            <div className="text-[10px] text-purple-400/80 font-mono mt-1">Morning boundary trap</div>
          </div>

          {/* +24-Hour Forecast */}
          <div className="p-3.5 rounded-xl bg-slate-900/90 border border-purple-800/60">
            <div className="flex items-center justify-between text-[10px] font-mono text-purple-300 mb-1">
              <span className="font-bold">24-HOUR FORECAST</span>
              <span className="px-1.5 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800">
                +24h
              </span>
            </div>
            <div className="text-xl font-black text-purple-200 font-mono">
              AQI {plus24h?.aqi}
            </div>
            <div className="text-[11px] text-slate-400 mt-1">
              PM2.5: <strong className="text-purple-300 font-mono">{plus24h?.pm25} µg</strong>
            </div>
            <div className="text-[10px] text-purple-400/80 font-mono mt-1">Diurnal dispersion</div>
          </div>

          {/* +48-Hour Forecast */}
          <div className="p-3.5 rounded-xl bg-slate-900/90 border border-purple-800/60 col-span-2 md:col-span-1">
            <div className="flex items-center justify-between text-[10px] font-mono text-purple-300 mb-1">
              <span className="font-bold">48-HOUR FORECAST</span>
              <span className="px-1.5 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800">
                +48h
              </span>
            </div>
            <div className="text-xl font-black text-emerald-400 font-mono">
              AQI {plus48h?.aqi}
            </div>
            <div className="text-[11px] text-slate-400 mt-1">
              PM2.5: <strong className="text-emerald-300 font-mono">{plus48h?.pm25} µg</strong>
            </div>
            <div className="text-[10px] text-emerald-400/80 font-mono mt-1">Anticipated ventilation</div>
          </div>
        </div>
      </div>

      {/* Interactive Forecast Horizon Chart */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Clock className="w-4 h-4 text-teal-400" />
              <span>Multi-Horizon Trajectory Chart (-24h Observed &rarr; +48h Predicted)</span>
            </h3>
            <p className="text-xs text-slate-400">
              Comparing verified historical ground measurements with auto-regressive model predictions.
            </p>
          </div>

          {/* Metric Selector (AQI, PM2.5, PM10) */}
          <div className="flex items-center gap-1.5 bg-slate-800 p-1 rounded-xl text-xs">
            {(['aqi', 'pm25', 'pm10'] as const).map(m => (
              <button
                key={m}
                onClick={() => setActiveMetric(m)}
                className={`px-3 py-1 rounded-lg font-bold font-mono transition uppercase ${
                  activeMetric === m
                    ? 'bg-teal-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {m}
              </button>
            ))}
          </div>
        </div>

        {/* Responsive SVG Chart */}
        <div className="relative w-full overflow-x-auto py-2">
          <svg
            viewBox={`0 0 ${chartWidth} ${chartHeight}`}
            className="w-full h-64 overflow-visible"
          >
            {/* Grid Lines */}
            <line
              x1={paddingX}
              y1={paddingY}
              x2={chartWidth - paddingX}
              y2={paddingY}
              stroke="#1e293b"
              strokeDasharray="4 4"
            />
            <line
              x1={paddingX}
              y1={chartHeight / 2}
              x2={chartWidth - paddingX}
              y2={chartHeight / 2}
              stroke="#1e293b"
              strokeDasharray="4 4"
            />
            <line
              x1={paddingX}
              y1={chartHeight - paddingY}
              x2={chartWidth - paddingX}
              y2={chartHeight - paddingY}
              stroke="#334155"
            />

            {/* Vertical Divider for NOW (Separating Observed vs Predicted) */}
            <line
              x1={getX(nowIndex)}
              y1={paddingY - 15}
              x2={getX(nowIndex)}
              y2={chartHeight - paddingY + 15}
              stroke="#38bdf8"
              strokeWidth="2"
              strokeDasharray="3 3"
            />
            <text
              x={getX(nowIndex)}
              y={paddingY - 20}
              textAnchor="middle"
              fill="#38bdf8"
              fontSize="10"
              fontFamily="monospace"
              fontWeight="bold"
            >
              [NOW / OBSERVED BOUNDARY]
            </text>

            {/* Observed Path (Solid Teal) */}
            <path
              d={observedPath}
              fill="none"
              stroke="#2dd4bf"
              strokeWidth="3.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />

            {/* Predicted Path (Dashed Purple) */}
            <path
              d={predictedPath}
              fill="none"
              stroke="#c084fc"
              strokeWidth="3.5"
              strokeDasharray="6 6"
              strokeLinecap="round"
              strokeLinejoin="round"
            />

            {/* Data Points */}
            {points.map((p, idx) => {
              const cx = getX(idx);
              const cy = getY(p[activeMetric]);
              const isNow = idx === nowIndex;
              const isObserved = p.type === 'observed';

              return (
                <g key={idx} className="group cursor-pointer">
                  {/* Outer glow ring for Current */}
                  {isNow && (
                    <circle
                      cx={cx}
                      cy={cy}
                      r="9"
                      fill="none"
                      stroke="#38bdf8"
                      strokeWidth="2"
                      className="animate-ping"
                    />
                  )}

                  {/* Dot */}
                  <circle
                    cx={cx}
                    cy={cy}
                    r={isNow ? '6' : '4.5'}
                    fill="#0f172a"
                    stroke={isObserved ? '#2dd4bf' : '#c084fc'}
                    strokeWidth="2.5"
                  />

                  {/* Value Label */}
                  <text
                    x={cx}
                    y={cy - 10}
                    textAnchor="middle"
                    fill={isObserved ? '#99f6e4' : '#e9d5ff'}
                    fontSize="10"
                    fontFamily="monospace"
                    fontWeight="bold"
                  >
                    {p[activeMetric]}
                  </text>

                  {/* X-axis Hour Label */}
                  <text
                    x={cx}
                    y={chartHeight - paddingY + 22}
                    textAnchor="middle"
                    fill="#94a3b8"
                    fontSize="9"
                    fontFamily="monospace"
                  >
                    {p.hourLabel}
                  </text>
                </g>
              );
            })}
          </svg>
        </div>

        {/* Chart Legend */}
        <div className="pt-2 border-t border-slate-800 flex flex-wrap items-center justify-between text-xs text-slate-400">
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1.5">
              <span className="w-4 h-1 bg-teal-400 rounded" />
              <span>Solid Line: <strong>Observed CAAQMS Sensor Readings</strong></span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-4 h-1 border-t-2 border-dashed border-purple-400" />
              <span>Dashed Line: <strong>Atmospheric Prototype Forecast</strong></span>
            </span>
          </div>
          <span className="font-mono text-[10px] text-slate-500">
            Model Engine: ARIMA-WRF-Dispersion-V1
          </span>
        </div>
      </div>
    </div>
  );
};
